export type mockQuestionsType = {
	question: string;
	answer1: string;
	answer2: string;
	answer3: string;
	answer4: string;
	correctAnswer: string;
	tags: string[];
	tag1?: string;
	tag2?: string;
	tag3?: string;
	tag4?: string;
	tag5?: string;
	tag6?: string;
	tag7?: string;
	difficulty: string;
	id: number;
	author: string;
	timeSubmitted: string;
	approved: boolean;
	approvedBy: string | null;
};

export const mockQuestions: mockQuestionsType[] = [
	{
		question: 'What is the capital city of Sweden?',
		answer1: 'Stockholm',
		answer2: 'Lund',
		answer3: 'Gothenburg',
		answer4: 'Uppsala',
		correctAnswer: 'Stockholm',
		tags: [
			'geography',
			'Europe',
			'Sweden',
			'Scandinavia',
			'countries',
			'capital city',
		],
		tag1: 'geography',
		tag2: 'Europe',
		tag3: 'Sweden',
		tag4: 'Scandinavia',
		tag5: 'countries',
		tag6: 'capital city',
		difficulty: 'easy',
		id: 1,
		author: 'demian.voksi@gmail.com',
		timeSubmitted: '2021-09-01T12:00:00Z',
		approved: true,
		approvedBy: 'demian.voksi@gmail.com',
	},
	{
		question:
			'What is the name of the official residence of the president of the United States of America?',
		answer1: 'The White House',
		answer2: '10 Downing Street',
		answer3: 'The Lodge',
		answer4: '24 Sussex Drive',
		correctAnswer: 'The White House',
		tags: ['politics', 'residence', 'building'],
		tag1: 'politics',
		tag2: 'residence',
		tag3: 'building',
		difficulty: 'easy',
		id: 2,
		author: 'demian.voksi@gmail.com',
		timeSubmitted: '2021-09-03T12:00:00Z',
		approved: true,
		approvedBy: 'demian.voksi@gmail.com',
	},
	{
		question:
			'What is the name of the first king of the Akkadian Empire, who ruled from c. 2334-2279 BC?',
		answer1: 'Dudu',
		answer2: 'Rimush',
		answer3: 'Naram-Sin',
		answer4: 'Sargon',
		correctAnswer: 'Sargon',
		tags: [
			'history',
			'Akkadian Empire',
			'Mesopotamia',
			'bronze age',
			'Middle East',
		],
		tag1: 'history',
		tag2: 'Akkadian Empire',
		tag3: 'Mesopotamia',
		tag4: 'bronze age',
		tag5: 'Middle East',
		difficulty: 'hard',
		id: 3,
		author: 'demian.voksi@gmail.com',
		timeSubmitted: '2021-09-03T12:00:00Z',
		approved: false,
		approvedBy: null,
	},
	{
		question:
			'What is the name of the Danish physicist who won the Nobel Prize in Physics in 1922?',
		answer1: 'Niels Bohr',
		answer2: 'Gustaf Dalen',
		answer3: 'Manne Siegbahn',
		answer4: 'Werner Heisenberg',
		correctAnswer: 'Niels Bohr',
		tags: ['Nobel Prize', 'science', 'physics', 'Denmark', 'Scandinavia'],
		tag1: 'Nobel Prize',
		tag2: 'science',
		tag3: 'physics',
		tag4: 'Denmark',
		tag5: 'Scandinavia',
		difficulty: 'medium',
		id: 4,
		author: 'demian.voksi@gmail.com',
		timeSubmitted: '2021-09-04T12:00:00Z',
		approved: true,
		approvedBy: 'demian.voksi@gmail.com',
	},
	// Continue this pattern for all remaining questions...
	{
		question: "How many circles of Hell are there in Dante's Inferno?",
		answer1: 'three',
		answer2: 'six',
		answer3: 'nine',
		answer4: 'twelve',
		correctAnswer: 'nine',
		tags: ['literature', 'Dante Alighieri', 'Middle Ages', 'Italy'],
		tag1: 'literature',
		tag2: 'Dante Alighieri',
		tag3: 'Middle Ages',
		tag4: 'Italy',
		difficulty: 'medium',
		id: 5,
		author: 'demian.voksi@gmail.com',
		timeSubmitted: '2021-09-05T12:00:00Z',
		approved: false,
		approvedBy: null,
	},
	{
		question:
			'Who is the top goal scorer for Manchester United Football Club through all of their professional matches?',
		answer1: 'Paul Scholes',
		answer2: 'Bobby Charlton',
		answer3: 'George Best',
		answer4: 'Wayne Rooney',
		correctAnswer: 'Wayne Rooney',
		tags: [
			'sports',
			'Manchester United',
			'soccer',
			'England',
			'Premier League',
		],
		tag1: 'sports',
		tag2: 'Manchester United',
		tag3: 'soccer',
		tag4: 'England',
		tag5: 'Premier League',
		difficulty: 'hard',
		id: 6,
		author: 'demian.voksi@gmail.com',
		timeSubmitted: '2021-09-06T12:00:00Z',
		approved: true,
		approvedBy: 'demian.voksi@gmail.com',
	},
	{
		question:
			'For which movie did the English cinematographer Roger Deakins win his first Academy Award for Best Cinematography?',
		answer1: 'Sicario',
		answer2: 'Blade Runner 2049',
		answer3: '1917',
		answer4: 'A Beautiful Mind',
		correctAnswer: 'Blade Runner 2049',
		tags: ['movies', 'cinematography', 'Academy Awards'],
		tag1: 'movies',
		tag2: 'cinematography',
		tag3: 'Academy Awards',
		difficulty: 'medium',
		id: 7,
		author: 'demian.voksi@gmail.com',
		timeSubmitted: '2021-09-07T12:00:00Z',
		approved: false,
		approvedBy: null,
	},
	{
		question: 'Which composer is the author of the opera Don Giovanni?',
		answer1: 'Antonio Vivaldi',
		answer2: 'Giuseppe Verdi',
		answer3: 'Wolfgang Amadeus Mozart',
		answer4: 'Richard Wagner',
		correctAnswer: 'Wolfgang Amadeus Mozart',
		tags: ['music', 'opera', 'composers'],
		tag1: 'music',
		tag2: 'opera',
		tag3: 'composers',
		difficulty: 'medium',
		id: 8,
		author: 'demian.voksi@gmail.com',
		timeSubmitted: '2021-09-08T12:00:00Z',
		approved: true,
		approvedBy: 'demian.voksi@gmail.com',
	},
	{
		question:
			'In which television show did the British actor Idris Elba play the character of Stringer Bell?',
		answer1: 'The Wire',
		answer2: 'Black Mirror',
		answer3: 'Breaking Bad',
		answer4: 'The Sopranos',
		correctAnswer: 'The Wire',
		tags: ['television'],
		tag1: 'television',
		difficulty: 'medium',
		id: 9,
		author: 'demian.voksi@gmail.com',
		timeSubmitted: '2021-09-09T12:00:00Z',
		approved: false,
		approvedBy: null,
	},
	{
		question: "What is the name of agent Mulder's sister in the show X-Files?",
		answer1: 'Alexandra',
		answer2: 'Sabrina',
		answer3: 'Laura',
		answer4: 'Samantha',
		correctAnswer: 'Samantha',
		tags: ['X-Files', 'television', 'shows'],
		tag1: 'X-Files',
		tag2: 'television',
		tag3: 'shows',
		difficulty: 'hard',
		id: 10,
		author: 'demian.voksi@gmail.com',
		timeSubmitted: '2021-09-10T12:00:00Z',
		approved: true,
		approvedBy: 'demian.voksi@gmail.com',
	},
	{
		question: 'What is the capital of France?',
		answer1: 'Paris',
		answer2: 'Strasbourg',
		answer3: 'Lyon',
		answer4: 'Bordeaux',
		correctAnswer: 'Paris',
		tags: ['France', 'capital city', 'geography', 'Europe'],
		tag1: 'France',
		tag2: 'capital city',
		tag3: 'geography',
		tag4: 'Europe',
		difficulty: 'easy',
		id: 11,
		author: 'demian.voksi@gmail.com',
		timeSubmitted: '2021-09-11T12:00:00Z',
		approved: false,
		approvedBy: null,
	},
	{
		question: 'How is the capital city of Madagascar spelled?',
		answer1: 'Anntananarivo',
		answer2: 'Antannanarivo',
		answer3: 'Antananarivo',
		answer4: 'Antanannarivo',
		correctAnswer: 'Antananarivo',
		tags: ['geography', 'Africa', 'Madagascar', 'islands'],
		tag1: 'geography',
		tag2: 'Africa',
		tag3: 'Madagascar',
		tag4: 'islands',
		difficulty: 'hard',
		id: 12,
		author: 'demian.voksi@gmail.com',
		timeSubmitted: '2021-09-12T12:00:00Z',
		approved: true,
		approvedBy: 'demian.voksi@gmail.com',
	},
	{
		question: 'What is the highest mountain in the world?',
		answer1: 'Mount Kilimanjaro',
		answer2: 'Mount Everest',
		answer3: 'K2',
		answer4: 'Denali',
		correctAnswer: 'Mount Everest',
		tags: ['mountains', 'geography'],
		tag1: 'mountains',
		tag2: 'geography',
		difficulty: 'easy',
		id: 13,
		author: 'demian.voksi@gmail.com',
		timeSubmitted: '2021-09-13T12:00:00Z',
		approved: false,
		approvedBy: null,
	},
	{
		question: 'Which ocean is the largest?',
		answer1: 'Atlantic Ocean',
		answer2: 'Indian Ocean',
		answer3: 'Arctic Ocean',
		answer4: 'Pacific Ocean',
		correctAnswer: 'Pacific Ocean',
		tags: ['oceans', 'geography', 'water', 'sea'],
		tag1: 'oceans',
		tag2: 'geography',
		tag3: 'water',
		tag4: 'sea',
		difficulty: 'easy',
		id: 14,
		author: 'demian.voksi@gmail.com',
		timeSubmitted: '2021-09-14T12:00:00Z',
		approved: true,
		approvedBy: 'demian.voksi@gmail.com',
	},
];
